
FROM cyclus/cymetric

RUN apt-get update
RUN apt-get install -y --force-yes wget
RUN apt-get install -y --force-yes python3-pip
RUN pip3 install sphinx sphinxcontrib-bibtex
RUN pip3 install cloud-sptheme==1.6

